site_name: Service Blueprints
nav:
- Domains and hosting:
   -  Domains: 'Domains-and-hosting/Domains.md'
   -  Domains Name System (DNS): 'Domains-and-hosting/DNS.md'
   -  Hosting: 'Domains-and-hosting/Hosting.md'
- Content Mapping:
   - Introduction : 'Content-Mapping/Introduction.md'
   - Data Collection : 'Content-Mapping/Data-Collection.md'
   - Building User Personas : 'Content-Mapping/Building-User-Personas.md'
   - Building User Journey : 'Content-Mapping/Building-User-Lifecycle.md'
   - Strategic Content Map: 'Content-Mapping/Strategic-content-map.md'
- Website Designing:
   - Introduction : 'Website-Designing/Introduction.md'
   - UI and UX : 'Website-Designing/UX-and-UI.md'
theme:
  name: material
  features:
    - instant
  font:
    text: Inter
    code: Source Code Pro
  palette:
      primary: indigo
      accent: blue

plugins:
  - search:
      prebuild_index: true
      lang:
        - en
  - git-revision-date-localized

markdown_extensions:
  - admonition
  - codehilite:
      guess_lang: false
  - toc:
      permalink: true
  - pymdownx.arithmatex
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.inlinehilite
  - pymdownx.magiclink
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.superfences
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.tabbed
  - pymdownx.tilde
